

#include "stm32l476xx.h"
#include "PWM.h" 
 
void PWM_Init() {
	// Enable GPIO Port E Clock
	RCC->AHB2ENR |= RCC_AHB2ENR_GPIOEEN;
	// Enable TIM1 Clock
	RCC->APB2ENR |= RCC_APB2ENR_TIM1EN;
	// Configure PE8
	GPIOE->MODER &= ~(GPIO_MODER_MODE8);
	//GPIOE->MODER |= GPIO_MODER_MODE8_1;
	GPIOE->OSPEEDR |= GPIO_OSPEEDR_OSPEED8;
	GPIOE->PUPDR &= ~(GPIO_PUPDR_PUPD8);
	
	//Configure PE10
	GPIOE->MODER &= ~(GPIO_MODER_MODE10);
	//GPIOE->MODER |= GPIO_MODER_MODE10_1;
	GPIOE->OSPEEDR |= GPIO_OSPEEDR_OSPEED10;
	GPIOE->PUPDR &= ~(GPIO_PUPDR_PUPD10);
	
	//Configure PE12
	GPIOE->MODER &= ~(GPIO_MODER_MODE12);
	GPIOE->MODER |= GPIO_MODER_MODE12_0;
	GPIOE->OSPEEDR |= GPIO_OSPEEDR_OSPEED12;
	GPIOE->PUPDR &= ~(GPIO_PUPDR_PUPD12);
	
	//Configure PE13
	GPIOE->MODER &= ~(GPIO_MODER_MODE13);
	GPIOE->MODER |= GPIO_MODER_MODE13_0;
	GPIOE->OSPEEDR |= GPIO_OSPEEDR_OSPEED13;
	GPIOE->PUPDR &= ~(GPIO_PUPDR_PUPD13);
	
	// Configure PWM Output for TIM1 CH 1N
	GPIOE->AFR[1] &= ~(GPIO_AFRH_AFSEL8);
	GPIOE->AFR[1] |= GPIO_AFRH_AFSEL8_0;
	
	// Configure PWM Output for TIM1 CH 2N
	GPIOE->AFR[1] &= ~(GPIO_AFRH_AFSEL10);
	GPIOE->AFR[1] |= GPIO_AFRH_AFSEL10_0;

	TIM1->CR1 &=  ~(TIM_CR1_DIR);
	TIM1->PSC = 3UL;
	TIM1->ARR = 1000UL;
	//Output compare mode
	TIM1->CCMR1 &= ~(TIM_CCMR1_OC1M);
	TIM1->CCMR1 |= TIM_CCMR1_OC1M_1;
	TIM1->CCMR1 |= TIM_CCMR1_OC1M_2;
	TIM1->CCMR1 |= TIM_CCMR1_OC1PE;
	
	TIM1->CCMR1 &= ~(TIM_CCMR1_OC2M);
	TIM1->CCMR1 |= TIM_CCMR1_OC2M_1;
	TIM1->CCMR1 |= TIM_CCMR1_OC2M_2;
	TIM1->CCMR1 |= TIM_CCMR1_OC2PE;
	
	TIM1->CCER &= ~(TIM_CCER_CC1NP);
	TIM1->CCER |= TIM_CCER_CC1NE;	
	
	TIM1->CCER &= ~(TIM_CCER_CC2NP);
	TIM1->CCER |= TIM_CCER_CC2NE;	
	
	TIM1->BDTR |= TIM_BDTR_MOE;
	TIM1->CCR1 &= ~(TIM_CCR1_CCR1);
	TIM1->CCR1 = 1000U;
	
	TIM1->CCR2 &= ~(TIM_CCR2_CCR2);
	TIM1->CCR2 = 1000U;
	TIM1->CR1 |= TIM_CR1_CEN;
	//TIM1->CCR1 = (1000U);
	
}
//PE10, PE13 right
//PE8, PE12 left

void PWM_forward(){
	GPIOE->ODR |= GPIO_ODR_OD12 | GPIO_ODR_OD13;
	GPIOE->MODER |= GPIO_MODER_MODE8_1;
	GPIOE->MODER |= GPIO_MODER_MODE10_1;
}

void PWM_reverse(){
	GPIOE->ODR &= ~(GPIO_ODR_OD12 | GPIO_ODR_OD13);
	GPIOE->MODER |= GPIO_MODER_MODE8_1;
	GPIOE->MODER |= GPIO_MODER_MODE10_1;
}

void PWM_stop() {
  GPIOE->MODER &= ~(GPIO_MODER_MODE8);
	GPIOE->MODER &= ~(GPIO_MODER_MODE10);
}

void PWM_right(){
	GPIOE->ODR |= GPIO_ODR_OD13;
	GPIOE->ODR &= ~(GPIO_ODR_OD12);
	GPIOE->MODER |= GPIO_MODER_MODE10_1;
	GPIOE->MODER |= GPIO_MODER_MODE8_1;
}
void PWM_left(){
	GPIOE->ODR &= ~(GPIO_ODR_OD13);
	GPIOE->ODR |= GPIO_ODR_OD12;
	GPIOE->MODER |= GPIO_MODER_MODE10_1;
	GPIOE->MODER |= GPIO_MODER_MODE8_1;
}

